name: Pruebas Automaticas
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch:

jobs:
  prueba_automatica:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm install
      - name : Autograde Testing
        run: npm run test -- --verbose 2>&1 | tee test.log
      - name : Show log file
        run: cat test.log
